#!/usr/bin/env zsh
# Re-register old widgets
for w in vi-delete vi-delete-char vi-kill-line vi-kill-eol \
	vi-change vi-change-eol vi-change-whole-line \
	vi-yank vi-yank-whole-line vi-yank-eol \
	vi-put-after vi-put-before vi-set-buffer
do
	zle -A ".$w" "$w"
done
# Unload functions
unhash -f -m '.evil-registers*' "$0"
