#!/usr/bin/env zsh
case $KEYMAP in
	(main|viins)*) __zvm_track_insert[c]=$CURSOR ;;
	*) [[ $__zvm_track_insert[m] = (main|viins)* ]] && \
		__zvm_track_insert[i]="${LBUFFER[__zvm_track_insert[c]+1,-1]:-$__zvm_track_insert[i]}" ;;
esac
__zvm_track_insert[m]=$KEYMAP
