#!/usr/bin/env zsh
if ! (( ${+ZSH_VIM_SYSTEM_PASTE_HANDLERS[$_zvsc_register]} )); then
	zle "$1"
	return "$?"
fi
# word splitting
CUTBUFFER="$(eval ${ZSH_VIM_SYSTEM_PASTE_HANDLERS[$_zvsc_register]})"
zle .vi-set-buffer ''
zle "$1"
unset _zvsc_register
