#!/usr/bin/env zsh
if ! (( ${+zvsc_paste_handlers[$_zvsc_register]} )); then
	zle "$1"
	return "$?"
fi
# word splitting
CUTBUFFER="$(eval ${zvsc_paste_handlers[$_zvsc_register]})"
zle .vi-set-buffer ''
zle "$1"
unset _zvsc_register
