#!/usr/bin/env zsh
local oldcutbuffer="$CUTBUFFER"
if (( ${+ZSH_EVIL_PASTE_HANDLERS[$_evil_register]} )); then
	CUTBUFFER="$(eval ${ZSH_EVIL_PASTE_HANDLERS[$_evil_register]})"
	zle .vi-set-buffer ''
elif [[ $_evil_register = [a-zA-Z] ]]; then
	case $ZSH_EVIL_SYNC_EDITOR in
		nvim*|neovim*|nvr)
			local reg
			reg="$(nvr --nostart -s --remote-expr "getreg(\"$_evil_register\")")"
			(( $#reg )) && registers[$_evil_register]="$reg"
		;;
		vim*)
			local reg
			[[ $(vim --version) = *+clientserver* ]] &&
				reg="$(vim --remote-expr "getreg(\"$_evil_register\")")"
			(( $#reg )) && registers[$_evil_register]="$reg"
		;;
	esac
fi
zle "$1"
CUTBUFFER="$oldcutbuffer"
unset _evil_register
